;  CS 218 - Assignment 8
;  Provided Main.

;  DO NOT EDIT THIS FILE

; --------------------------------------------------------------------
;  Write four assembly language functions.

;  The void function, gnomeSort(), sorts the numbers into ascending
;  order (small to large).  Uses the gnome sort algorithm from
;  assignment #7 (modified to sort in descending order).

;  The void function, basicStats(), finds the minimum, median, and
;  maximum, sum, and average for a list of numbers.
;  The median is determined after the list is sorted by the 
;  using the listMedian function.

;  The value returning function, listMedian(), computes the 
;  median of the list.

;  The  value returning function, corrCoefficient(), computes the
;  correlation coefficient for the two data sets.
;  Note, summation and division performed as integer values.
;  Due to the data sizes, the summation for the dividend (top)
;  must be performed as a quad-word.

; ----------

section	.data

; -----
;  Define standard constants.

TRUE		equ	1
FALSE		equ	0

EXIT_SUCCESS	equ	0			; Successful operation

STDIN		equ	0			; standard input
STDOUT		equ	1			; standard output
STDERR		equ	2			; standard error

SYS_read	equ	0			; call code for read
SYS_write	equ	1			; call code for write
SYS_open	equ	2			; call code for file open
SYS_close	equ	3			; call code for file close
SYS_fork	equ	57			; call code for fork
SYS_exit	equ	60			; call code for terminate
SYS_creat	equ	85			; call code for file open/create
SYS_time	equ	201			; call code for get time

LF		equ	10
NULL		equ	0
ESC		equ	27

; -----
;  Data Sets for Assignment #8.

xList1		dd	 121,   27,   10,   22,   61
		dd	  15,   12,  120,   19,   20
		dd	  20,   11,   12
yList1		dd	1230, 1233, 1323, 1241, 1360
		dd	1290, 1118, 1250, 1475, 1423
		dd	1210, 1337, 1226
len1		dd	13
xMin1		dd	0
xMed1		dd	0
xMax1		dd	0
xSum1		dd	0
xAve1		dd	0
yMin1		dd	0
yMed1		dd	0
yMax1		dd	0
ySum1		dd	0
yAve1		dd	0
r1		dq	0


xList2		dd	 127,  135,  117,  115,  261
		dd	 210,  220,  222,  224,  226
		dd	 129,  113,  155,  235,  237
		dd	 219,  241,  143,  245,  149
		dd	 153,  119,  223,  117,  259
		dd	 116,  115,  251,  267,  169
		dd	 228,  230,  132,  133,  221
		dd	 138,  240,  142,  244,  246
		dd	 221,  125,  251,  213,  119
		dd	 157,  299,  153,  265,  279
yList2		dd	 127,  155,  217,  115,  161
		dd	 283,  214,  121,  228,  212
		dd	 126,  117,  227,  127,  284
		dd	 174,  212,  125,  126,  229
		dd	 288,  215,  111,  118,  215
		dd	 126,  117,  215,  210,  114
		dd	 124,  243,  134,  212,  113
		dd	 172,  276,  256,  265,  156
		dd	 253,  140,  291,  268,  162
		dd	 246,  247,  167,  177,  144
len2		dd	50
xMin2		dd	0
xMed2		dd	0
xMax2		dd	0
xSum2		dd	0
xAve2		dd	0
yMin2		dd	0
yMed2		dd	0
yMax2		dd	0
ySum2		dd	0
yAve2		dd	0
r2		dq	0


xList3		dd	  44,   34,   13,   21,   16
		dd	  41,   33,   24,   13,   23
		dd	  18,   43,   12,   10,   10
		dd	  24,   43,   24,   12,   23
		dd	  53,   40,   11,   18,   12
		dd	  47,   27,    9,   17,   19
		dd	  83,   50,    1,   28,   15
		dd	  83,   14,   11,   18,   12
		dd	  26,   17,   17,   17,   14
		dd	  74,   12,   15,   16,   29
		dd	  18,    5,   11,   18,   15
		dd	  26,   17,   15,    3,   14
		dd	  24,   13,   14,   12,   13
		dd	  72,   26,   16,   15,   16
		dd	  53,   10,   11,   18,   12
		dd	  46,   17,   17,   17,   14
		dd	  55,   12,   15,   19,   14
		dd	  64,    2,   15,   12,   12
		dd	  83,   15,   11,   18,   11
		dd	  66,   17,   17,   17,   14
yList3		dd	 310,  220,  232,  324,  326
		dd	 319,  313,  235,  235,  337
		dd	 339,  341,  243,  245,  249
		dd	 253,  219,  213,  210,  229
		dd	 216,  215,  351,  367,  219
		dd	 328,  330,  332,  233,  321
		dd	 238,  340,  242,  244,  346
		dd	 321,  325,  351,  213,  219
		dd	 257,  339,  253,  365,  379
		dd	 227,  355,  317,  215,  211
		dd	 383,  314,  311,  328,  312
		dd	 226,  217,  227,  227,  314
		dd	 318,  315,  311,  218,  315
		dd	 226,  217,  215,  211,  314
		dd	 324,  343,  334,  312,  213
		dd	 322,  276,  356,  265,  356
		dd	 253,  240,  291,  368,  322
		dd	 246,  247,  367,  377,  244
		dd	 255,  332,  385,  249,  314
		dd	 364,  372,  275,  262,  372
len3		dd	100
xMin3		dd	0
xMed3		dd	0
xMax3		dd	0
xSum3		dd	0
xAve3		dd	0
yMin3		dd	0
yMed3		dd	0
yMax3		dd	0
ySum3		dd	0
yAve3		dd	0
r3		dq	0


; --------------------------------------------------------

extern	gnomeSort, basicStats, corrCoefficient

section	.text
global	_start
_start:


; **************************************************
;  Call functions for data set 1.

;  call gnomeSort(xList1, len1)
	mov	rdi, xList1
	mov	esi, dword [len1]
	call	gnomeSort

;  call gnomeSort(yList1, len1)
	mov	rdi, yList1
	mov	esi, dword [len1]
	call	gnomeSort

;  call basicStats(xList1, len1, xMin1, xMed1, xMax1, xSum1, xAve1)
	mov	rdi, xList1
	mov	esi, dword [len1]
	mov	rdx, xMin1
	mov	rcx, xMed1
	mov	r8, xMax1
	mov	r9, xSum1
	mov	rax, xAve1
	push	rax
	call	basicStats
	add	rsp, 8

;  call basicStats(yList1, len1, yMin1, yMed1, yMax1, ySum1, yAve1)
	mov	rdi, yList1
	mov	esi, dword [len1]
	mov	rdx, yMin1
	mov	rcx, yMed1
	mov	r8, yMax1
	mov	r9, ySum1
	mov	rax, yAve1
	push	rax
	call	basicStats
	add	rsp, 8

;  r1 = corrCoefficient(xList1, yList1, len1)
	mov	rdi, xList1
	mov	rsi, yList1
	mov	edx, dword [len1]
	call	corrCoefficient
	movsd	qword [r1], xmm0


; **************************************************
;  Call functions for data set 2.

;  call gnomeSort(xList2, len2)
	mov	rdi, xList2
	mov	esi, dword [len2]
	call	gnomeSort

;  call gnomeSort(yList2, len2)
	mov	rdi, yList2
	mov	esi, dword [len2]
	call	gnomeSort

;  call basicStats(xList2, len2, xMin2, xMed2, xMax2, xSum2, xAve2)
	mov	rdi, xList2
	mov	esi, dword [len2]
	mov	rdx, xMin2
	mov	rcx, xMed2
	mov	r8, xMax2
	mov	r9, xSum2
	mov	rax, xAve2
	push	rax
	call	basicStats
	add	rsp, 8

;  call basicStats(yList2, len2, yMin2, yMed2, yMax2, ySum2, yAve2)
	mov	rdi, yList2
	mov	esi, dword [len2]
	mov	rdx, yMin2
	mov	rcx, yMed2
	mov	r8, yMax2
	mov	r9, ySum2
	mov	rax, yAve2
	push	rax
	call	basicStats
	add	rsp, 8

;  r2 = corrCoefficient(xList2, yList2, len2)
	mov	rdi, xList2
	mov	rsi, yList2
	mov	edx, dword [len2]
	call	corrCoefficient
	movsd	qword [r2], xmm0


; **************************************************
;  Call functions for data set 3.

;  call gnomeSort(xList3, len3)
	mov	rdi, xList3
	mov	esi, dword [len3]
	call	gnomeSort

;  call gnomeSort(yList3, len3)
	mov	rdi, yList3
	mov	esi, dword [len3]
	call	gnomeSort

;  call basicStats(xList3, len3, xMin3, xMed3, xMax3, xSum3, xAve3)
	mov	rdi, xList3
	mov	esi, dword [len3]
	mov	rdx, xMin3
	mov	rcx, xMed3
	mov	r8, xMax3
	mov	r9, xSum3
	mov	rax, xAve3
	push	rax
	call	basicStats
	add	rsp, 8

;  call basicStats(yList3, len3, yMin3, yMed3, yMax3, ySum3, yAve3)
	mov	rdi, yList3
	mov	esi, dword [len3]
	mov	rdx, yMin3
	mov	rcx, yMed3
	mov	r8, yMax3
	mov	r9, ySum3
	mov	rax, yAve3
	push	rax
	call	basicStats
	add	rsp, 8

;  r3 = corrCoefficient(xList3, yList3, len3)
	mov	rdi, xList3
	mov	rsi, yList3
	mov	edx, dword [len3]
	call	corrCoefficient
	movsd	qword [r3], xmm0


; ******************************
;  Done, terminate program.

last:
	mov	rax, SYS_exit
	mov	rdi, EXIT_SUCCESS
	syscall

